workflow:
    - publishss
shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo the main jobs started!
    publishss:
        steps:
            - sleep: sleep 120
            - set-env: ./set-env.sh
            - get-env: echo $FOO
            - install: npm install semantic-release
            - publish: npm run semantic-release
            - check-version: ./check-version.sh
            - fail: exit 1
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
