workflow:
    - publish
shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo the main jobs started!
    publish:
        steps:
            - install: npm install semantic-release
            - publish: npm publish
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
