workflow:
    - publish
shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo the main jobs started!
    publishss:
        steps:
            - install: npm install semantic-release
            - publish: npm run semantic-release
            - check-version: ./check-version.sh
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
